### PR TITLE
map --help to help command

### PR DESCRIPTION
**Pull request by nichtich**
Fixes issue #30

### CODE REVIEW

**Comment by rjbs** [comment]
@nichtich I have a bunch of PRs from you, and I hope to get to them soon.  Sorry for the delays!

**Comment by nichtich** [comment]
Any estimated schedule to include PR 47,48,49,50? ;-)

**Comment by rjbs** [comment]
This added a test to basic.t but did not increase the test count!

**Comment by rjbs** [comment]
I retract my statement.  git was just being too clever for my own good!

**Comment by rjbs** [comment]
Thanks, merged.  I had to fix a little bug in Dist::Zilla, because it didn't call the SUPER::global_opt_spec :)

**Pull request closed without merging**
